### ISSUE TITLE
Bot recap title might include wrong date

### ISSUE THREAD

**Issue by stringlapse** [Uncreate/tretkibot#20]
Requires more investigation

**Comment by Uncreate** [comment]
File "/home/AtomRigs/Tretki/TretkiBot.py", line 6, in <module>
    now = datetime.datetime.now().astimezone(datetime.timezone(datetime.timedelta(hours=-7), 'Mountain Standard Time'))
AttributeError: 'module' object has no attribute 'timezone'

**Comment by stringlapse** [comment]
Fixed in minimal branch, this branch is now deprecated
